# read data from text file
f = open("ganesha.txt","rt")
c = f.readline()
print(c)
c = f.readline()
print(c)
c= f.readline()
print(c)
c=f.readline()
print(c)
c=f.read()
print(c,end="")
f.close()
f = open("Biodata.txt","rt")
c =f.read()
print(c)